### ISSUE TITLE
[Bug]: Problems as of version 1.4.3 on Android

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/Butterfly#280] opened 2022-08-28 21:17 UTC
### What happened?

Here is a video showcasing UI and UX problems in Butterfly on Android.

Part 1: 

[landscape.webm](https://user-images.githubusercontent.com/173219/187093904-a0c21fb8-c33d-432f-b05b-ff38d380a260.webm)

Part 2:

[portrait.webm](https://user-images.githubusercontent.com/173219/187094096-0952bb50-e154-4987-9f6d-0912410a3282.webm)

List of problems:

* Setting brush small stroke width is inconvenient, especially using onscreen keyboard in landscape mode
* Additional settings (besides stroke width and multiplier) are hidden. You need to **know** they exists in order to guess that you need to scroll down. Needs some scroll bar.
* Too much vertical space is eaten by toolbars in landscape mode. I'd prefer colour toolbar to be scrollable, but fit inside main toolbar. File title may be hidden under main menu.
* **Trying to draw too close to the screen edge when Android is in "Gesture navigation" mode leads to problems.** Maybe Butterfly receives mouse down (or whatever) event, but not mouse up and things that a finger is being constantly touched.
* No easy way to draw & shrink. Sometimes you need to draw or write text while looking at another part of the scene. Drawing with finger is crude, so figures get big. For observation a figure can be small. That leads iteratively developed thing to get bigger and bigger with no [obvious] way to shrink it.
* Area tool looks like a rectangular selection tool, but is actually grouping tool (if I understand correctly). And it is not clear how to move objects into/out from groups.
* Areas require names. I expect them to be auto-named like "Area 1", "Area 2", with renaming as additional step, if user desires. Also typing the name in landscape mode is ugly.
* (not reproduced in this run). Sometimes path-erasing a lot of stokes leaves "ghosts" behind (i.e. un-repainted parts of screen showing old strokes which disappear if I exit and reopen Butterfly).
* Undo is less accessible in the portrait mode. Requires three taps instead of one and you don't immediately see the effect of the undo.
* **Sometimes repaints fail during panning and zooming**. You need to force redrawing by reloading Butterfly, drawing something in the "bind spot" or changing screen orientation back and forth to workaround this.
* (not depicted - too lazy to create another Github issue) Tapping to select individual strokes does not prioritie smallest possible stoke. I can choose what exactly I want to select from a further popup, but I'd prefer the first option to be the smallest matching stroke. I'd also ordered them not just by bounding box, but also whether I tapped on the line itself or just near it. I.e. if there is a drawing of "©" symbol (two strokes) and I click on "C", then it should offer options whether to select "C" or "O", but "C" should be the first (it is smaller). Clicking exactly at the line should further boost the sorting priority. This may also be idea for precise path eraser - erase only things that actually intersect the erasing line you draw, not just near it.

Serious problems are emphasised by bold style.

### Version

1.4.3.40 from F-Droid.

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2022-08-29 05:13
Thanks for this bug report!
These are very many problems. The bigger ones will be fixed as 1.4.4, the smaller ones will i fix in the next 1.5 update.

> Setting brush small stroke width is inconvenient, especially using onscreen keyboard in landscape mode

The problem is the small display size. I  will try to fix that

> Additional settings (besides stroke width and multiplier) are hidden. 

You have already a scroll bar if you scroll. I will change it so that it is always visible

> Too much vertical space is eaten by toolbars in landscape mode

Yeah, the landscape mode is tricky. I find the document name very useful, maybe I will hide these information if you don't have enough place.

> Trying to draw too close to the screen edge when Android is in "Gesture navigation" mode leads to problems

I need to investigate how I can fix this problem.

> No easy way to draw & shrink

I will try to add a new feature to resize it (1.5).

> Area tool looks like a rectangular selection tool, but is actually grouping tool (if I understand correctly). 

In the next version it will have a monitor icon. This should help. It's not a grouping tool, it's a way to restrict the infinite viewport to export it for example.

> Areas require names

To name it `Area 1`, ... is a good idea. I will add it.

> Sometimes path-erasing a lot of stokes leaves "ghosts" behind

I thought I fixed it. I will see that I will fix it soon (1.4.4)

> Undo is less accessible in the portrait mode

Already fixed in #257. You can add it in your toolbar if you wish.

> Sometimes repaints fail during panning and zooming

Strange, I will look at it.

> Tapping to select individual strokes does not prioritie smallest possible stoke.

I will add it in the next update (1.5).

**Comment by vi** [comment] 2022-08-29 08:05
> The problem is the small display size.

I don't think 6.3-inch screen is considered small.
Maybe Butterfly's UI can be scaled down in general, so all UI elements are 1.5x smaller? Can it be adjustable setting?

**Comment by vi** [comment] 2022-08-29 08:07
>> "ghosts" after path-erasing
> I thought I fixed it. I will see that I will fix it soon (1.4.4)

Note that I remember reproducing it in previous F-Droid version (1.4.3). Maybe it is indeed already fixed.

**Comment by CodeDoctorDE** [comment] 2022-08-31 17:02
> > The problem is the small display size.
> 
> I don't think 6.3-inch screen is considered small (for a smartphone). Maybe Butterfly's UI can be scaled down in general, so all UI elements are 1.5x smaller? Can it be adjustable setting?

The scale is determined by the system. 



> > > "ghosts" after path-erasing
> 
> > I thought I fixed it. I will see that I will fix it soon (1.4.4)
> 
> Note that I remember reproducing it in previous F-Droid version (1.4.3). Maybe it is indeed already fixed, if there are recent changes in that feature.

Can you please try if it was already fixed? That would help me a lot

**Comment by vi** [comment] 2022-08-31 17:08
> Can you please try if it was already fixed? That would help me a lot

Tried to provoke it and failed to reproduce so far.
Consider it not relevant. I'll address it again if that happens again.

**Comment by CodeDoctorDE** [comment] 2022-09-03 12:05
Can you try the latest alpha? I fixed most of the problems

**Closed** 2022-09-21 11:01 UTC
Labels: bug, confirmed
