### ISSUE TITLE
[Feature request]: Ability to remove hand tool from toolbar

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#256] opened 2022-08-18 15:38 UTC
### Is your feature request related to a problem? Please describe

I would like to be able to remove the hand tool (pan/zoom) from the tool bar because I don't use it at all, since the wonderful gestures already fullfil its role for me. 

### Describe your feature request!

The pan tool can be turned into a normal tool, like pen or eraser, so the already great customizability can be leveraged. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2022-08-18 15:40
Hmm, the problem is that the current implementation of the gestures has no option to select elements without the tool.
But I can add the option to remove it if you want

**Comment by solarkraft** [comment] 2022-08-18 15:53
Hm, what did I miss? I wasn't able to noticeably select any elements using the panning tool, both with my stylus and my finger. 

Wouldn't this be a good opportunity for a selection tool?

**Comment by CodeDoctorDE** [comment] 2022-08-18 15:55
![image](https://user-images.githubusercontent.com/20452814/185440092-78250276-e0b8-477b-9a75-9661788a46d9.png)
You can select elements by clicking on it. The hand tool should be the selection tool

**Comment by solarkraft** [comment] 2022-08-18 16:01
Hm, doesn't work for me. Tracking in #260

**Comment by CodeDoctorDE** [comment] 2022-08-18 16:54
If I add the selection functionality in #259, can we close this issue?

**Comment by solarkraft** [comment] 2022-08-18 17:21
> But I can add the option to remove it if you want

Preferably rather if this is done :-)

But it could be done independently of other issues, since it only adds a choice (I for instance currently don't use the selection features anyway).

**Comment by CodeDoctorDE** [comment] 2022-08-18 17:26
Okay, thanks for the idea

**Comment by CodeDoctorDE** [comment] 2022-09-02 11:50
Fixed in 1.5.0-alpha.1

**Closed by CodeDoctorDE** 2022-09-02 11:50 UTC
Labels: enhancement
